spring:
  datasource:
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/shopping_cart"
    username: "postgres"
    password: "12345"
  jpa:
    hibernate:
      ddl-auto: none # Отключение автоматического изменения структуры таблиц
    properties:
      hibernate:
        format_sql: true # Форматирует SQL-запросы для удобства чтения
        show_sql: false # Показывает SQL-запросы в логах
        jdbc:
          lob:
            non_contextual_creation: true # Ускорение работы с большими объектами (LOB)
  data:
    web:
      pageable:
        serialization-mode: via_dto
  sql:
    init:
      mode: always
logging:
  level:
    root: INFO
    org.zalando.logbook: TRACE